// import './globals.css'
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{ margin: "10px" }}>
          <Link href="/" style={{ margin: "5px" }}>
            홈
          </Link>
          <Link href="/about" style={{ margin: "5px" }}>
            List
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
